language: java

matrix:
  include:
    - os: linux
      sudo: required
      jdk: openjdk11

script: ./gradlew test --info --stacktrace --console=plain --max-workers=1 --no-daemon --build-cache -Dkotlin.colors.enabled=false
